In [ ]:
import numpy as np
import pandas as pd
df=pd.read_csv('/content/nvidia_data.csv')
df

   Close_Price_USD    Volume  PE_Ratio  Daily_Return
0           124.36  61300885     60.29       -0.0056
1           138.77  44981505     45.18        0.0485
2           133.30  53953367     45.58        0.0020
3           129.97  58544107     58.12        0.0374
4           118.90  44521373     55.00        0.0212
5           118.90  79574309     46.17        0.0005
6           116.45  43344769     69.34       -0.0388
7           136.65  73657787     50.82        0.0448
8           130.03  74817184     47.27        0.0107
9           132.70  71642059     60.46       -0.0053

In [ ]:
df.head()

   Close_Price_USD    Volume  PE_Ratio  Daily_Return
0           124.36  61300885     60.29       -0.0056
1           138.77  44981505     45.18        0.0485
2           133.30  53953367     45.58        0.0020
3           129.97  58544107     58.12        0.0374
4           118.90  44521373     55.00        0.0212

In [ ]:
df.Volume.fillna(df.Volume.mode()[0],inplace=True)
features=df.iloc[:,:-1].values

/tmp/ipykernel_872/1102864783.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df.Volume.fillna(df.Volume.mode()[0],inplace=True)

In [ ]:
label=df.iloc[:,-1].values

In [ ]:
from sklearn.impute import SimpleImputer
age=SimpleImputer(strategy="mean",missing_values=np.nan)
Salary=SimpleImputer(strategy="mean",missing_values=np.nan)
age.fit(features[:,[1]])

SimpleImputer()

In [ ]:
Salary.fit(features[:,[2]])

SimpleImputer()

In [ ]:
SimpleImputer()

SimpleImputer()

In [ ]:
features[:,[1]]=age.transform(features[:,[1]])

In [1]:
features[:,[2]]=Salary.transform(features[:,[2]])

NameError: name 'Salary' is not defined

In [ ]:
features

array([[1.2436000e+02, 6.1300885e+07, 6.0290000e+01],
       [1.3877000e+02, 4.4981505e+07, 4.5180000e+01],
       [1.3330000e+02, 5.3953367e+07, 4.5580000e+01],
       [1.2997000e+02, 5.8544107e+07, 5.8120000e+01],
       [1.1890000e+02, 4.4521373e+07, 5.5000000e+01],
       [1.1890000e+02, 7.9574309e+07, 4.6170000e+01],
       [1.1645000e+02, 4.3344769e+07, 6.9340000e+01],
       [1.3665000e+02, 7.3657787e+07, 5.0820000e+01],
       [1.3003000e+02, 7.4817184e+07, 4.7270000e+01],
       [1.3270000e+02, 7.1642059e+07, 6.0460000e+01]])

In [ ]:
from sklearn.preprocessing import OneHotEncoder
oh = OneHotEncoder(sparse_output=False)
Country=oh.fit_transform(features[:,[0]])
Country

array([[0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0.]])

In [ ]:
final_set=np.concatenate((Country,features[:,[1,2]]),axis=1)

In [ ]:
final_set

array([[0.0000000e+00, 0.0000000e+00, 1.0000000e+00, 0.0000000e+00,
        0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
        0.0000000e+00, 6.1300885e+07, 6.0290000e+01],
       [0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
        0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
        1.0000000e+00, 4.4981505e+07, 4.5180000e+01],
       [0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
        0.0000000e+00, 0.0000000e+00, 1.0000000e+00, 0.0000000e+00,
        0.0000000e+00, 5.3953367e+07, 4.5580000e+01],
       [0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 1.0000000e+00,
        0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
        0.0000000e+00, 5.8544107e+07, 5.8120000e+01],
       [0.0000000e+00, 1.0000000e+00, 0.0000000e+00, 0.0000000e+00,
        0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
        0.0000000e+00, 4.4521373e+07, 5.5000000e+01],
       [0.0000000e+00, 1.0000000e+00, 0.0000000e+00, 0.0000000e+00,
        0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
        0.0000000e+00, 7.9574309e+07, 4.6170000e+01],
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
        0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
        0.0000000e+00, 4.3344769e+07, 6.9340000e+01],
       [0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
        0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 1.0000000e+00,
        0.0000000e+00, 7.3657787e+07, 5.0820000e+01],
       [0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
        1.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
        0.0000000e+00, 7.4817184e+07, 4.7270000e+01],
       [0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
        0.0000000e+00, 1.0000000e+00, 0.0000000e+00, 0.0000000e+00,
        0.0000000e+00, 7.1642059e+07, 6.0460000e+01]])

In [ ]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
sc.fit(final_set)
feat_standard_scaler=sc.transform(final_set)
feat_standard_scaler

array([[-0.33333333, -0.5       ,  3.        , -0.33333333, -0.33333333,
        -0.33333333, -0.33333333, -0.33333333, -0.33333333,  0.05111293,
         0.83511203],
       [-0.33333333, -0.5       , -0.33333333, -0.33333333, -0.33333333,
        -0.33333333, -0.33333333, -0.33333333,  3.        , -1.19917661,
        -1.11610844],
       [-0.33333333, -0.5       , -0.33333333, -0.33333333, -0.33333333,
        -0.33333333,  3.        , -0.33333333, -0.33333333, -0.51180827,
        -1.06445469],
       [-0.33333333, -0.5       , -0.33333333,  3.        , -0.33333333,
        -0.33333333, -0.33333333, -0.33333333, -0.33333333, -0.16009428,
         0.55489043],
       [-0.33333333,  2.        , -0.33333333, -0.33333333, -0.33333333,
        -0.33333333, -0.33333333, -0.33333333, -0.33333333, -1.23442907,
         0.15199116],
       [-0.33333333,  2.        , -0.33333333, -0.33333333, -0.33333333,
        -0.33333333, -0.33333333, -0.33333333, -0.33333333,  1.45110918,
        -0.98826541],
       [ 3.        , -0.5       , -0.33333333, -0.33333333, -0.33333333,
        -0.33333333, -0.33333333, -0.33333333, -0.33333333, -1.32457316,
         2.00377816],
       [-0.33333333, -0.5       , -0.33333333, -0.33333333, -0.33333333,
        -0.33333333, -0.33333333,  3.        , -0.33333333,  0.99782201,
        -0.38779054],
       [-0.33333333, -0.5       , -0.33333333, -0.33333333,  3.        ,
        -0.33333333, -0.33333333, -0.33333333, -0.33333333,  1.08664781,
        -0.84621759],
       [-0.33333333, -0.5       , -0.33333333, -0.33333333, -0.33333333,
         3.        , -0.33333333, -0.33333333, -0.33333333,  0.84338945,
         0.85706488]])

In [ ]:
from sklearn.preprocessing import MinMaxScaler
mms=MinMaxScaler(feature_range=(0,1))
mms.fit(final_set)
feat_minmax_scaler=mms.transform(final_set)
feat_minmax_scaler

array([[0.        , 0.        , 1.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.49562087,
        0.62541391],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 1.        , 0.04517684,
        0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 1.        , 0.        , 0.        , 0.29281625,
        0.01655629],
       [0.        , 0.        , 0.        , 1.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.41952887,
        0.53559603],
       [0.        , 1.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.03247637,
        0.40645695],
       [0.        , 1.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 1.        ,
        0.04097682],
       [1.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        1.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 1.        , 0.        , 0.83669343,
        0.23344371],
       [0.        , 0.        , 0.        , 0.        , 1.        ,
        0.        , 0.        , 0.        , 0.        , 0.86869486,
        0.08650662],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        1.        , 0.        , 0.        , 0.        , 0.78105574,
        0.63245033]])